import logging
import requests
from django.conf import settings
from requests import HTTPError
import base64
import subprocess


class HomeCenterAdapter:
    """
        Adapter that handles the data that are generated by the Fibaro sensors
    """

    def __init__(self):
        """Basic data initialization"""
        self.password = settings.HC_PASSWORD
        self.url = settings.HC_URL
        self.user = settings.HC_USER
        hash_constructor = self.user + ':' + self.password
        to_encode = hash_constructor.encode('ascii')
        encoded = base64.b64encode(to_encode).decode('utf-8')

        self.token = encoded

        self.headers = {
            'Authorization': f"Basic {self.token}"
        }

    def get(self, endpoint='', method='Get', parameters=''):
        """
        Description of get

        Args:
            self:
            endpoint (Text): the endpoing of the URL eg /api/device/new_device
            method (Text):
            parameters (Text): Stores a string with the parameters that are used to make the call

        """
        

        try:
            response = requests.request(method,
                                        self.url+endpoint,
                                        headers=self.headers,
                                        params=parameters
                                        )
            return response
        except (requests.exceptions.ConnectionError, requests.exceptions.InvalidURL) as ex:
            print('Wrong HCL IP. Calling get_ip.sh')
            result = subprocess.call('./get_ip.sh', shell=True)
            print('Success')
        