import logging
import requests
from django.conf import settings
from requests import HTTPError
import base64


class HomeCenterAdapter:
    """
        Adapter that handles the data that are generated by the Fibaro sensors
    """

    def __init__(self):
        """Basic data initialization"""
        self.password = settings.HC_PASSWORD
        self.url = settings.HC_URL
        self.user = settings.HC_USER
        hash_constructor = self.user + ':' + self.password
        to_encode = hash_constructor.encode('ascii')
        encoded = base64.b64encode(to_encode).decode('utf-8')

        self.token = encoded

        self.headers = {
            'Authorization': f"Basic {self.token}"
        }

    def get(self, endpoint='', method='Get', parameters=''):
        """
        Fetches data from the Home Center Lite API
        """

        try:
            response = requests.request(method,
                                        self.url+endpoint,
                                        headers=self.headers,
                                        params=parameters
                                        )
            return response
        except HTTPError as ex:
            logging.warning(ex)
