import json
import logging
from django.contrib.postgres.fields import JSONField
from django.db import models
from scheduler.Fibaro import tasks as fibaro


class Device(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.TextField()
    room_id = models.IntegerField()
    device_type = models.TextField()
    baseType = models.TextField()
    enabled = models.BooleanField()
    visible = models.BooleanField()
    is_plugin = models.BooleanField()
    parent_id = models.ForeignKey('self', on_delete=models.CASCADE, related_name='device', null=True)
    remote_gateway_id = models.IntegerField(null=True)
    view_xml = models.BooleanField(null=True)
    config_xml = models.BooleanField(null=True)
    interfaces = JSONField()
    properties = JSONField()
    actions = JSONField()
    created = models.IntegerField()
    modified = models.IntegerField()
    sort_order = models.IntegerField()

    def read_json(self, device_dict):
        self.id = device_dict.get('id')
        self.name = device_dict.get('name')
        self.room_id = device_dict.get('roomID')
        self.device_type = device_dict.get('type')
        self.baseType = device_dict.get('baseType')
        self.enabled = device_dict.get('enabled')
        self.visible = device_dict.get('visible')
        self.is_plugin = device_dict.get('isPlugin')
        self.parent_id = Device.objects.get(pk=device_dict.get('parentId'))
        self.remote_gateway_id = device_dict.get('remoteGatewayId')
        self.view_xml = device_dict.get('viewXml')
        self.config_xml = device_dict.get('configXml')
        self.interfaces = json.dumps(device_dict.get('interfaces'))
        self.actions = json.dumps(device_dict.get('actions'))
        self.created = device_dict.get('created')
        self.modified = device_dict.get('modified')
        self.sort_order = device_dict.get('sortOrder')
        self.properties = json.dumps(device_dict.get('properties'))


class EventBase(models.Model):
    event_id = models.IntegerField(primary_key=True)
    event_type = models.TextField()
    timestamp = models.IntegerField()
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    device_type = models.TextField()
    property_name = models.TextField(null=True)
    value = models.IntegerField(null=True)
    event = models.TextField(null=True)

    def read_json(self, event_dict):
        try:
            self.event_id = event_dict.get('id')
            self.event_type = event_dict.get('type')
            self.timestamp = event_dict.get('timestamp')
            self.device = Device.objects.get(pk=event_dict.get('deviceID'))
            self.device_type = event_dict.get('deviceType')
            self.property_name = event_dict.get('propertyName')
            self.value = event_dict.get('newValue')
            if 'event' in event_dict.keys():
                self.event = event_dict.get('event').get('data').get('keyAttribute')
            else:
                self.event = None
        except models.ObjectDoesNotExist:
            logging.info("Device ID:{}".format(event_dict.get('deviceID')))
            fibaro.get_sensor_data()


# class DeviceProperties(models.Model):
#     UIMessageSendTime = models.IntegerField(null=True)
#     autoConfig = models.IntegerField(null=True)
#     armConfig = models.TextField(null=True)
#     alarmDelay = models.TextField(null=True)
#     armError = models.TextField(null=True)
#     armed = models.TextField(null=True)
#     alarmExclude = models.TextField(null=True)
#     alarmTimeTimestamp = models.TextField(null=True)
#     batteryLevel = models.IntegerField(null=True)
#     batteryLowNotification = models.TextField(null=True)
#     configured = models.BooleanField()
#     date = models.TextField(null=True)
#     dead = models.BooleanField()
#     deviceControlType = models.IntegerField()
#     deviceIcon = models.IntegerField()
#     disabled = models.IntegerField(null=True)
#     emailNotificationID = models.IntegerField()
#     emailNotificationType = models.IntegerField()
#     endPoint = models.IntegerField(null=True)
#     endPointId = models.IntegerField()
#     fibaroAlarm = models.BooleanField(null=True)
#     interval = models.IntegerField(null=True)
#     homeIdHash = models.TextField(null=True)
#     lastBreached = models.TextField(null=True)
#     liliOffCommand = models.TextField(null=True)
#     liliOnCommand = models.TextField(null=True)
#     log = models.TextField()
#     logTemp = models.TextField()
#     manufacturer = models.TextField()
#     markAsDead = models.BooleanField()
#     model = models.TextField()
#     nodeId = models.IntegerField()
#     parameters = JSONField()
#     parametersTemplate = models.IntegerField()
#     pendingActions = models.BooleanField(null=True)
#     pollingDeadDevice = models.BooleanField(null=True)
#     pollingTime = models.IntegerField(null=True)
#     pollingTimeNext = models.IntegerField(null=True)
#     pollingTimeSec = models.IntegerField()
#     productInfo = models.TextField()
#     pushNotificationID = models.IntegerField()
#     pushNotificationType = models.IntegerField(null=True)
#     remoteGatewayId = models.IntegerField(null=True)
#     requestNodeNeighborStatTimeStemp = models.TextField(null=True)
#     requestNodeNeighborState = models.TextField(null=True)
#     requestNodeNeighborStateTimeStemp = models.TextField(null=True)
#     saveLogs = models.BooleanField()
#     serialNumber = models.TextField()
#     showChildren = models.TextField(null=True)
#     smsNotificationID = models.IntegerField()
#     smsNotificationType = models.IntegerField()
#     status = models.TextField(null=True)
#     sunriseHour = models.TextField(null=True)
#     sunsetHour = models.TextField(null=True)
#     useTemplate = models.BooleanField()
#     userDescription = models.TextField()
#     value = JSONField()
#     wakeUpTime = models.IntegerField(null=True)
#     zwaveBuildVersion = models.TextField(null=True)
#     zwaveCompany = models.TextField()
#     zwaveInfo = models.TextField()
#     zwaveRegion = models.TextField(null=True)
#     zwaveVersion = models.TextField()
